name = "giveaway-bot"
type = "webpack"
main = "./src/server.js"
route = ''
usage_model = 'bundled'
compatibility_flags = []
workers_dev = true
node_compat = true
compatibility_date = "2022-09-12"


[env.production]
vars = { DISCORD_PUBLIC_KEY = "", DISCORD_APPLICATION_ID = "" }
DISCORD_APPLICATION_ID = ""
DISCORD_PUBLIC_KEY = ""
DISCORD_TOKEN = ""
